routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

app/Models/City.php
<?php

namespace PKMS\Models;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $table = 'm_cities';
    protected $hidden = ['id','province_id'];

    public function districts()
    {
        return $this->hasMany('PKMS\District','city_id','code');
    }

    public function getNameAttribute($value)
    {
        return ucwords(strtolower($value));
    }
}

app/Models/Faq.php
<?php

namespace PKMS\Models;

use Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use PKMS\Events\ArticleUpdated;
use PKMS\Models\User;
use PKMS\Models\Task;
use PKMS\Models\Komment;
use PKMS\Models\MasterArticleCode;
use PKMS\Models\MasterArticleSubcode;
use Carbon\Carbon;

class Faq extends Model
{
    protected $table = 'pkms_faqs';
    protected $guarded = [];
    protected $appends = ['share_url', 'bookmarked', 'small_img', 'medium_img', 'original_img', 'pembaruan', 'slug'];

    /**
     * Mutators
     */

    public function getCreatedAtAttribute($value)
    {
        return date('d M Y', strtotime($value));
    }

    public function getUpdatedAtAttribute($value)
    {
        return date('d M Y', strtotime($value));
    }

    public function setTagsAttribute($value)
    {
        $this->attributes['tags'] = ($value) ? implode(',', $value) : NULL;
    }

    public function getShareUrlAttribute()
    {
        return url('view', ['id' => $this->attributes['id']]);
    }

    public function getSmallImgAttribute()
    {
        return '/images/small/'.$this->attributes['image'];
    }

    public function getMediumImgAttribute()
    {
        return '/images/medium/'.$this->attributes['image'];
    }

    public function getOriginalImgAttribute()
    {
        return '/images/original/'.$this->attributes['image'];
    }

    public function getBookmarkedAttribute()
    {
        if (Auth::guard('api')->check()) {
            $book = Auth::guard('api')->user()->knowledges()->pluck('faq_id')->toArray();
            if (in_array($this->attributes['id'], $book)) {
                return 1;
            }
            return 0;
        }
        return 0;
    }

    public function getPembaruanAttribute()
    {
        $update = Carbon::parse($this->attributes['updated_at']);
        $nowdate= Carbon::now();
        if ($update->diffInDays($nowdate) <= 3) {
            return 1;
        }
        return 0;
    }

    public function getSlugAttribute()
    {
        return str_slug($this->attributes['title'], '-');
    }

    public function bookmarked()
    {
        return $this->belongsToMany('PKMS\Models\User', 'pkms_faq_bookmarks', 'user_id', 'faq_id');
    }

    public function getNmklasifikasiAttribute()
    {
        if ($this->attributes['klasifikasi'] == 1) {
            return 'Infografis';
        }

        if ($this->attributes['klasifikasi'] == 2) {
            return 'Studi kasus';
        }

        if ($this->attributes['klasifikasi'] == 3) {
            return 'Video';
        }

        if ($this->attributes['klasifikasi'] == 4) {
            return 'Materi paparan';
        }
    }

    /**
     * Relationships
     */

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function articlecode()
    {
        return $this->hasOne(MasterArticleCode::class, 'id', 'article_code');
    }

    public function articlesubcode()
    {
        return $this->hasOne(MasterArticleSubcode::class, 'id', 'article_subcode');
    }

    public function comments()
    {
        return $this->hasMany(Komment::class);
    }
}

app/Models/Task.php
<?php

namespace PKMS\Models;

use Illuminate\Database\Eloquent\Model;
use Esensi\Model\Contracts\ValidatingModelInterface;
use Esensi\Model\Traits\ValidatingModelTrait;
use PKMS\Models\User;
use PKMS\Models\Rating;
use PKMS\Models\Article;
use PKMS\Models\Attachment;
use PKMS\Models\Comment;
use PKMS\Events\TaskUpdate;

class Task extends Model implements ValidatingModelInterface
{
    use ValidatingModelTrait;

    protected $table = 't_tasks';
    protected $guarded = [];
    protected $rules = [
        'title'         => ['required'],
        'description'   => ['required']
    ];
    protected $events = [
        'updated' => TaskUpdate::class
    ];

    public function completed()
    {
        return $this->where('is_completed',1);
    }

    /**
     * Mutators
     */

    public function getAssignedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    public function getAcceptedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    public function getCompletedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    public function getCreatedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    public function getUpdatedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    /**
     * Relationships
     */

    public function assignedby()
    {
        return $this->hasOne(User::class,'id', 'assigned_by');
    }

    public function assignedto()
    {
        return $this->hasOne(User::class, 'id', 'assigned_to');
    }

    public function postedby()
    {
        return $this->hasOne(User::class, 'id', 'posted_by');
    }

    public function rating()
    {
        return $this->hasOne(Rating::class);
    }

    public function articles()
    {
        return $this->belongsToMany(Article::class, 'p_article_task');
    }

    public function comments()
    {
        return $this->belongsToMany(Comment::class, 'p_comment_task');
    }

    public function attachments()
    {
        return $this->belongsToMany(Attachment::class, 'p_attachment_task');
    }
}

resources/views/_box_profile.blade.php
@php

$cache = Cache::remember('user_'. Auth::user()->id, 30, function () {
    return [
        'average_rating' => Auth::user()->averageRating()->first(),
        'unread_message' => Auth::user()->inbox()->where('read', 0)->get()
    ];
});

@endphp

<div class="panel panel-default visible-md visible-lg">
    <div class="panel-body" align="center">
        <img src="{{ Auth::user()->avatar ? secure_asset('storage/'.Auth::user()->avatar) : secure_asset('img/default_avatar.jpg') }}" alt="avatar" width="128px" height="128px" class="img img-circle img-responsive img-thumbnail">
    </div>
    <table class="table">
        <tr>
            <th colspan="3" class="text-center">
                <a href="{{route('expert.profile')}}">{{Auth::user()->name}}</a>
            </th>
        </tr>

        @if(!Auth::user()->is_admin)
            <tr>
                <td colspan="3" class="text-center">
                    @if($cache['average_rating'])
                        @php
                            $avg_rating = $cache['average_rating']->aggeragate;
                            $star = 0;
                        @endphp

                        @for($i = 0; $i < floor($avg_rating); $i++, $star++)
                            <i class="fa fa-star bg-yellow"></i>
                        @endfor

                        @if(fmod($avg_rating, 1))
                            @php
                                $star++;
                            @endphp
                            <i class="fa fa-star-half-empty bg-yellow"></i>
                        @endif

                        @for($i = 1; $i < $star; $i++)
                            <i class="fa fa-star-o bg-yellow"></i>
                        @endfor

                    @else
                        @for($i = 0; $i < 5; $i++)
                            <i class="fa fa-star-o bg-yellow"></i>
                        @endfor
                    @endif
                </td>
            </tr>
        @endif

        <tr>
            <td colspan="3" class="text-center">
                <a href="{{route('expert.messages')}}"><i class="fa fa-fw fa-envelope-o"></i>
                    Inbox &nbsp;
                    @if($cache['unread_message']->count())
                        <span class="badge badge-danger">{{$cache['unread_message']->count()}}</span>
                    @endif
                </a>
            </td>
        </tr>
    </table>
</div>

@if(!request()->session()->get('incomplete', false))
    <div class="list-group visible-md visible-lg">
        <a href="{{route('expert.tasks')}}" class="list-group-item"><i class="fa fa-fw fa-tasks"></i> Tugas</a>
        <a href="{{route('expert.articles')}}" class="list-group-item"><i class="fa fa-fw icon-docs"></i> Tulisan</a>
        <a href="{{route('expert.packets')}}" class="list-group-item"><i class="fa fa-fw fa-columns"></i> Paket</a>
    </div>
@endif

resources/views/_incomplete.blade.php
@if(request()->session()->get('incomplete', false))
    <div class="alert alert-warning">
        <i class="fa fa-exclamation-circle"></i> {!! request()->session()->get('incomplete', false) !!}
    </div>
@endif

resources/views/educations.blade.php
@extends('layouts.app')

@section('content')

<div id="educations-page" class="container">

    @include('_incomplete')

    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa icon-graduation"></i> Edukasi</div>
        @if($user->educations->count())
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Institusi</th>
                            <th>Jurusan / Bidang keahlian</th>
                            <th>Nilai</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($user->educations()->orderBy('education_id','asc')->get() as $education)
                            <tr>
                                <td>{{$education->detail->code}} - {{$education->name}}</td>
                                <td>{{$education->major}}</td>
                                <td>{{$education->gpa}}</td>
                                <td>
                                    {!! Former::open(route('expert.educations.delete', $education->id))->method('delete') !!}
                                        <a href="{{route('expert.educations.edit', $education->id)}}" class="btn btn-default">Edit</a>
                                        <button class="btn btn-delete btn-danger">Hapus</button>
                                    {!! Former::close() !!}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @else
            <div class="panel-body">
                <div class="alert alert-warning">
                    Anda belum memasukan data riwayat pendidikan.
                </div>
            </div>
        @endif
        <div class="panel-footer">
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-education">
                <i class="fa fa-fw fa-plus"></i> Tambah riwayat pendidikan
            </button>
        </div>
    </div>
</div>

{{-- Modal edukasi  --}}
<div id="modal-education" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Riwayat pendidikan</h4>
            </div>
            {!! Former::open(route('expert.educations.create')) !!}
                <div class="modal-body">
                    {!! Former::select('education_id')->label('Tingkat Pendidikan')->placeholder('Pilih')->fromQuery(PKMS\Models\MasterEducation::get(), 'name', 'id')->required() !!}
                    {!! Former::text('name')->label('Nama Institusi Pendidikan')->placeholder('Nama Institusi Pendidikan')->required() !!}
                    {!! Former::text('major')->label('Nama Jurusan / Bidang Keahlian')->placeholder('Nama Jurusan / Bidang Keahlian (Opsional)') !!}
                    {!! Former::text('gpa')->label('Nilai / Peringkat Kelulusan / GPA')->placeholder('Nilai (Opsional)') !!}
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    <button class="btn btn-primary">Simpan</button>
                </div>
            {!! Former::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/educations_edit.blade.php
@extends('layouts.app')

@section('content')

<div id="educations-page" class="container">

    @include('_incomplete')

    <div class="panel panel-default">
        <div class="panel-heading">Edit Edukasi</div>
        {!! Former::populate($education) !!}
        {!! Former::open(route('expert.educations.update', $education_id)) !!}
            <div class="panel-body">
                {!! Former::select('education_id')->label('Tingkat Pendidikan')->placeholder('Pilih')->fromQuery(PKMS\Models\MasterEducation::get(), 'name', 'id')->required() !!}
                {!! Former::text('name')->label('Nama Institusi Pendidikan')->placeholder('Nama Institusi Pendidikan')->required() !!}
                {!! Former::text('major')->label('Nama Jurusan / Bidang Keahlian')->placeholder('Nama Jurusan / Bidang Keahlian (Opsional)') !!}
                {!! Former::text('gpa')->label('Nilai / Peringkat Kelulusan / GPA')->placeholder('Nilai (Opsional)') !!}
            </div>

            <div class="panel-footer">
                <button class="btn btn-primary">Simpan</button>
                <a href="{{route('expert.educations')}}" class="btn btn-default">Kembali</a>
            </div>
        {!! Former::close() !!}
    </div>
</div>

@endsection

resources/views/tasks.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @include('_box_profile')
        </div>

        <div class="col-md-10">

            @include('_incomplete')

            {{-- Tugas Baru  --}}
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-fw fa-info"></i> Tugas Masuk</div>

                @if($new_tasks->count())
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="120">Tgl Terima</th>
                                    <th width="175">Judul</th>
                                    <th width="250">Deskripsi</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($new_tasks as $task)
                                    <tr>
                                        <td>{{$task->assigned_at}}</td>
                                        <td><a href="{{route('expert.tasks.detail', $task->id)}}">{{$task->title}}</a></td>
                                        <td>{{str_limit($task->description, 100)}}</td>
                                        <td align="right">
                                            <div class="btn-group btn-group-sm">
                                                <a href="{{route('expert.tasks.accept', $task->id)}}" class="btn btn-accept btn-default"><i class="fa fa-check text-success"></i> Terima</a>
                                                <a href="{{route('expert.tasks.deny', $task->id)}}" class="btn btn-deny btn-default"><i class="fa fa-times text-danger"></i> Tolak</a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="panel-body">
                        <p>Tidak ada penugasan baru.</p>
                    </div>
                @endif
            </div>

            {{-- Tugas Berjalan  --}}
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-fw fa-tasks"></i> Tugas berjalan</div>

                @if($my_tasks->count())
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="120">Tgl Penugasan</th>
                                    <th width="175">Judul</th>
                                    <th width="250">Deskripsi</th>
                                    <th>Progress</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($my_tasks as $task)
                                    <tr>
                                        <td>{{$task->accepted_at}}</td>
                                        <td><a href="{{route('expert.tasks.detail', $task->id)}}">{{$task->title}}</a></td>
                                        <td>{{str_limit($task->description, 100)}}</td>
                                        <td>
                                            <div class="progress">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="{{$task->progress}}" aria-valuemin="0" aria-valuemax="100" style="width: {{$task->progress}}%;">{{$task->progress}}%</div>
                                            </div>
                                        </td>
                                        <td>
                                            {{ ($task->progress >= 100) ? 'Menunggu approval' : 'Belum selesai' }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="panel-body">
                        <p>Belum ada tugas yang sedang berjalan.</p>
                    </div>
                @endif
            </div>

            {{-- Tugas Selesai --}}
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-fw fa-check text-success"></i> Tugas selesai</div>
                @if($completed_tasks->count())
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="120">Tgl Penugasan</th>
                                    <th width="175">Judul</th>
                                    <th width="250"Deskripsi</th>
                                    <th>Rating</th>
                                    <th>Review</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($completed_tasks as $task)
                                    <tr>
                                        <td>{{$task->accepted_at}}</td>
                                        <td><a href="{{route('expert.tasks.detail', $task->id)}}">{{$task->title}}</a></td>
                                        <td>{{str_limit($task->description, 100)}}</td>
                                        <td>
                                            @for($i = 0; $i < floor($task->rating->rating); $i++)
                                                <i class="fa fa-star bg-yellow"></i>
                                            @endfor

                                            @if(fmod($task->rating->rating, 1))
                                                <i class="fa fa-star-half bg-yellow"></i>
                                            @endif
                                        </td>
                                        <td>{{$task->rating->review or '-'}}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="panel-body">
                        <p>Belum ada tugas yang selesai.</p>
                    </div>
                @endif
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/tasks_detail.blade.php
@extends('layouts.app')

@section('content')
<div id="task-detail-page" class="container">
    <div class="row">
        <div class="col-md-2">
            @include('_box_profile')
        </div>

        <div class="col-md-10">

            @include('_incomplete')

            {{-- Breadcrumb  --}}
            <ol class="breadcrumb">
                <li><a href="{{route('expert.tasks')}}"><i class="fa fa-fw fa-tasks"></i> Tugas</a></li>
                <li class="active">Detail - ID : {{$task->id}}, Title: {{$task->title}}</li>
            </ol>

            {{-- Task Detail --}}
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-fw fa-info"></i> Tugas</div>

                @if($task->is_accepted)
                    {!! Former::populate($task) !!}
                    {!! Former::open(route('expert.tasks.update', $task->id)) !!}
                        <div class="panel-body">
                            {!! Former::text('title')->label('Judul')->disabled() !!}
                            {!! Former::textarea('description')->label('Deskripsi')->rows(5)->disabled() !!}

                            @if(!$task->is_completed)
                                {!! Former::number('progress')->max(100)->min(0)->append('%') !!}
                            @else
                                {!! Former::number('progress')->max(100)->min(0)->append('%')->disabled() !!}

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Tgl Mulai Pelaksanaan</label>
                                            <div class="form-control">{{$task->accepted_at}}</div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Tgl Selesai Pelaksanaan</label>
                                            <div class="form-control">{{$task->completed_at}}</div>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>Status</label>
                                    <div class="form-control"><i class="fa fa-fw fa-check text-success"></i> Telah selesai</div>
                                </div>
                            @endif
                        </div>

                        @if(!$task->is_completed)
                            <div class="panel-footer">
                                <button class="btn btn-success">Update Progress</button>
                            </div>
                        @endif
                    {!! Former::close() !!}
                @else
                    {!! Former::populate($task) !!}
                    {!! Former::open()->method('get') !!}
                        <div class="panel-body">
                            {!! Former::text('title')->label('Judul')->disabled() !!}
                            {!! Former::textarea('description')->label('Deskripsi')->rows(5)->disabled() !!}
                        </div>
                    {!! Former::close() !!}

                    <div class="panel-footer">
                        <a href="{{route('expert.tasks.accept', $task->id)}}" class="btn btn-accept btn-default"><i class="fa fa-check text-success"></i> Terima</a>
                        <a href="{{route('expert.tasks.deny', $task->id)}}" class="btn btn-deny btn-default"><i class="fa fa-times text-danger"></i> Tolak</a>
                    </div>
                @endif
            </div>

            {{-- Related Articles  --}}
            @if($task->is_accepted)
                <div class="panel panel-default">
                    <div class="panel-heading"><i class="fa icon-docs"></i> Artikel terkait</div>
                    @if($task->articles->count())
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Penulis</th>
                                        <th>Revisi</th>
                                        <th>Update terakhir</th>
                                        <th>Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($task->articles as $article)
                                        <tr>
                                            <td><a href="{{route('expert.articles.view', $article->id)}}" data-toggle="modal" data-target="#modal-view-article">{{$article->title}}</a></td>
                                            <td>{{$article->author->name}}</td>
                                            <td>{{$artile->revision or '-'}}</td>
                                            <td>{{$article->updated_at or $article->created_at}}</td>
                                            <td>{{$article->is_published ? 'Terbit' : 'Belum terbit'}}</td>
                                            <td>
                                                @if(!$task->is_completed)
                                                    {!! Former::open(route('expert.articles.delete', $article->id))->method('delete') !!}
                                                        <a href="{{route('expert.articles.edit', $article->id)}}" class="btn btn-sm btn-default">Edit</a>
                                                        <button class="btn btn-sm btn-danger btn-delete">Hapus</button>
                                                    {!! Former::close() !!}
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="panel-body">
                            <p>Tidak ada artikel terkait.</p>
                        </div>
                    @endif
                    <div class="panel-footer">
                        <a href="{{route('expert.tasks.add_article', $task->id)}}" class="btn btn-default"><i class="fa fa-fw fa-plus"></i> Buat Artikel</a>
                    </div>
                </div>

                {{-- Related Comments  --}}
                <div class="panel panel-default">
                    <div class="panel-heading"><i class="fa fa-fw fa-envelope-o"></i> Pesan terkait</div>
                    <div class="panel-body">
                        @if($task->comments->count())
                            <div class="media-lists comments">
                                @foreach($task->comments as $comment)
                                    <div class="media">
                                        <div class="media-left">
                                            <a href="javascript:;">
                                                <img class="media-object img-circle" height="64px" width="64px" src="{{$comment->author->avatar ? secure_asset('storage/'. $comment->author->avatar) : secure_asset('/img/default_avatar.jpg') }}">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading">{{$comment->author->name}} <small>{{$comment->updated_at or $comment->created_at}}</small></h4>
                                            <p>{{$comment->text}}</p>
                                            @if($comment->attachments->count())
                                                <ul class="list-inline">
                                                    @foreach($comment->attachments as $attachment)
                                                        <li><a href="{{secure_asset('storage/'.$attachment->path)}}" target="_blank" class="btn btn-sm btn-default"><i class="fa fa-fw fa-paperclip"></i> {{$attachment->title}}</a></li>
                                                    @endforeach
                                                </ul>
                                            @endif
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        @else
                            <p>Tidak ada pesan terkait.</p>
                        @endif
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">Pesan baru</div>
                    {!! Former::open_for_files(route('expert.tasks.add_comment', $task->id)) !!}
                        <div class="panel-body">
                            {!! Former::textarea('text')->label('Pesan')->placeholder('pesan')->rows(5)->required() !!}
                            {!! Former::file('lampiran[]')->label('Lampiran')->multiple()->accept('.jpg, .jpeg, .png, .bmp, .pdf, .docx, .doc, .ppt, .pptx, .zip, .rar, .xls, .xlsx') !!}
                        </div>
                        <div class="panel-footer">
                            <button class="btn btn-success"><i class="fa fa-fw fa-send"></i> Kirim pesan</button>
                        </div>
                    {!! Former::close() !!}
                </div>
            @endif
        </div>
    </div>
</div>

{{-- Modal Article --}}
@if($task->is_accepted)

    {{-- Modal View Article  --}}
    <div id="modal-view-article" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
@endif

@endsection