routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

app/Models/City.php
<?php

namespace PKMS\Models;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $table = 'm_cities';
    protected $hidden = ['id','province_id'];

    public function districts()
    {
        return $this->hasMany('PKMS\District','city_id','code');
    }

    public function getNameAttribute($value)
    {
        return ucwords(strtolower($value));
    }
}

app/Models/Task.php
<?php

namespace PKMS\Models;

use Illuminate\Database\Eloquent\Model;
use Esensi\Model\Contracts\ValidatingModelInterface;
use Esensi\Model\Traits\ValidatingModelTrait;
use PKMS\Models\User;
use PKMS\Models\Rating;
use PKMS\Models\Article;
use PKMS\Models\Attachment;
use PKMS\Models\Comment;
use PKMS\Events\TaskUpdate;

class Task extends Model implements ValidatingModelInterface
{
    use ValidatingModelTrait;

    protected $table = 't_tasks';
    protected $guarded = [];
    protected $rules = [
        'title'         => ['required'],
        'description'   => ['required']
    ];
    protected $events = [
        'updated' => TaskUpdate::class
    ];

    public function completed()
    {
        return $this->where('is_completed',1);
    }

    /**
     * Mutators
     */

    public function getAssignedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    public function getAcceptedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    public function getCompletedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    public function getCreatedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    public function getUpdatedAtAttribute($value)
    {
        return ($value) ? date('d M y', strtotime($value)) : '-';
    }

    /**
     * Relationships
     */

    public function assignedby()
    {
        return $this->hasOne(User::class,'id', 'assigned_by');
    }

    public function assignedto()
    {
        return $this->hasOne(User::class, 'id', 'assigned_to');
    }

    public function postedby()
    {
        return $this->hasOne(User::class, 'id', 'posted_by');
    }

    public function rating()
    {
        return $this->hasOne(Rating::class);
    }

    public function articles()
    {
        return $this->belongsToMany(Article::class, 'p_article_task');
    }

    public function comments()
    {
        return $this->belongsToMany(Comment::class, 'p_comment_task');
    }

    public function attachments()
    {
        return $this->belongsToMany(Attachment::class, 'p_attachment_task');
    }
}

app/Models/User.php
<?php

namespace PKMS\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Esensi\Model\Contracts\ValidatingModelInterface;
use Esensi\Model\Traits\ValidatingModelTrait;
use Esensi\Model\Contracts\PurgingModelInterface;
use Esensi\Model\Traits\PurgingModelTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;
use PKMS\Events\UserRegistered;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable implements ValidatingModelInterface, PurgingModelInterface
{
    use HasApiTokens;
    use Notifiable;
    use ValidatingModelTrait;
    use PurgingModelTrait;

    protected $table = 't_users';
    protected $guarded = [];
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $rules = [
        'name'          => ['required','min:3'],
        'email'         => ['required', 'email', 'unique'],
        'username'      => ['required','min:3', 'unique'],
        'password'      => ['required']
    ];
    protected $purgeable = [
        'old_password'
    ];
    protected $events = [
        'created' => UserRegistered::class
    ];

    /**
     * Mutators
     */

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = ucwords($value);
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    // public function getAvatarAttribute($value)
    // {
    //     return asset('storage/'. $value);
    // }

    /**
     * Helper
     */

    public function averageRating()
    {
        return $this->ratings()->selectRaw('avg(rating) as aggeragate, user_id')
            ->groupBy('user_id');
    }

    // For expert user to gain acces to task, they need to completed their profile, education & experiences
    public function isComplete()
    {
        return $this->hasProfile() && $this->hasExperience() && $this->educations();
    }

    public function hasProfile()
    {
        return $this->profile()->count();
    }

    public function hasExperience()
    {
        return $this->experiences()->count();
    }

    public function hasEducation()
    {
        return $this->educations()->count();
    }

    public function knowledges()
    {
        return $this->belongsToMany('PKMS\Models\Faq', 'pkms_faq_bookmarks', 'user_id', 'faq_id');
    }

    public function pasals()
    {
        return $this->belongsToMany('PKMS\Models\Pasal', 'pkms_pasal_bookmarks', 'user_id', 'pasal_id');
    }

    public function discuss()
    {
        return $this->belongsToMany('PKMS\Models\Question', 'pkms_diskusi_bookmarks', 'user_id', 'question_id');
    }

    /**
     * Relationships
     */

    public function inbox()
    {
        return $this->hasMany('PKMS\Models\Message', 'to');
    }

    public function outbox()
    {
        return $this->hasMany('PKMS\Models\Message', 'from');
    }

    public function my_tasks()
    {
        return $this->hasMany('PKMS\Models\Task', 'assigned_to');
    }
    
    public function my_packets()
    {
        return $this->hasMany('PKMS\Models\Packet', 'assigned_to');
    }

    public function task_history()
    {
        return $this->hasMany('PKMS\Models\TaskHistory', 'user_id');
    }
    
    public function packet_history()
    {
        return $this->hasMany('PKMS\Models\PacketHistory', 'user_id');
    }

    public function profile()
    {
        return $this->hasOne('PKMS\Models\Profile');
    }

    public function experiences()
    {
        return $this->hasMany('PKMS\Models\Experience');
    }

    public function educations()
    {
        return $this->hasMany('PKMS\Models\Education');
    }

    public function ratings()
    {
        return $this->hasMany('PKMS\Models\Rating');
    }

    public function interests()
    {
        return $this->belongsToMany('PKMS\Models\Interest', 'p_user_interest');
    }

    public function tasks()
    {
        return $this->hasMany('PKMS\Models\Task', 'assigned_to');
    }
    
    public function packets()
    {
        return $this->hasMany('PKMS\Models\Packet', 'assigned_to');
    }

    public function offers()
    {
        return $this->hasMany('PKMS\Models\PacketOffer', 'user_id');
    }

    public function usulans()
    {
        return $this->hasMany('PKMS\Models\Usulan', 'user_id');
    }
    
    public function packetRatings()
    {
        return $this->hasMany('PKMS\Models\PacketOffer', 'user_id');
    }

    public function token()
    {
        return $this->hasOne('PKMS\Models\FcmToken', 'user_id');
    }

    public function likes()
    {
        return $this->belongsToMany('PKMS\Models\Faq', 'pkms_user_like_usulans', 'user_id', 'usulan_id')->withTimestamps();
    }

    public function highlights()
    {
        return $this->belongsTo(Highlight::class, 'user_id');
    }
}

resources/views/modules/admin/tasks/_detail_accepted.blade.php
{!! Former::populate($task) !!}
{!! Former::open(route('admin.tasks.update', $task->id)) !!}
    <div class="panel-body">
        {!! Former::text('title')->label('Judul')->required() !!}
        {!! Former::textarea('description')->label('Deskripsi')->rows(5) !!}

        @if(!$task->is_completed)
            {!! Former::number('progress')->max(100)->min(0)->append('%') !!}
        @else
            {!! Former::number('progress')->max(100)->min(0)->append('%')->disabled() !!}

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Tgl Mulai Pelaksanaan</label>
                        <div class="form-control">{{$task->accepted_at}}</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Tgl Selesai Pelaksanaan</label>
                        <div class="form-control">{{$task->completed_at}}</div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label>Status</label>
                <div class="form-control"><i class="fa fa-fw fa-check text-success"></i> Telah selesai</div>
            </div>
        @endif
    </div>

    @if(!$task->is_completed)
        <div class="panel-footer">
            <button class="btn btn-default">Update</button>
            <div class="pull-right">
                <a href="javascript:;" data-task-id="{{$task->id}}" data-task-title="{{$task->title}}" data-toggle="modal" data-target="#modal-approve-task" class="btn btn-approve btn-sm btn-success">Approve Tugas</a>
            </div>
        </div>
    @endif
{!! Former::close() !!}

resources/views/modules/admin/tasks/_detail_articles.blade.php
@if($task->articles->count())
<div class="panel panel-default">
    <div class="panel-heading"><i class="fa icon-docs"></i> Artikel terkait</div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Penulis</th>
                    <th>Revisi</th>
                    <th>Update terakhir</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($task->articles as $article)
                    <tr>
                        <td><a href="{{route('admin.articles.view', $article->id)}}" data-toggle="modal" data-target="#modal-view-article">{{$article->title}}</a></td>
                        <td>{{$article->author->name}}</td>
                        <td>{{$article->revision or '-'}}</td>
                        <td>{{$article->updated_at or $article->created_at}}</td>
                        <td>{{$article->is_published ? 'Terbit' : 'Belum terbit'}}</td>
                        <td>
                            @if(!$task->is_completed)
                                <div class="btn-group btn-group-sm">
                                    <a href="{{route('admin.articles.edit', $article->id)}}" class="btn btn-default">Edit</a>
                                </div>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endif

resources/views/modules/admin/tasks/_detail_comments.blade.php
{{-- Related Comments  --}}
<div class="panel panel-default">
    <div class="panel-heading"><i class="fa fa-fw fa-envelope-o"></i> Pesan terkait</div>
    <div class="panel-body">
        @if($task->comments->count())
            <div class="media-lists comments">
                @foreach($task->comments as $comment)
                    <div class="media">
                        <div class="media-left">
                            <a href="javascript:;">
                                <img class="media-object img-circle" height="64px" width="64px" src="{{$comment->author->avatar ? secure_asset('storage/'. $comment->author->avatar) : secure_asset('/img/default_avatar.jpg') }}">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">{{$comment->author->name}} <small>{{$comment->updated_at or $comment->created_at}}</small></h4>
                            <p>{{$comment->text}}</p>
                            @if($comment->attachments->count())
                                <ul class="list-inline">
                                    @foreach($comment->attachments as $attachment)
                                        <li><a href="{{route('admin.attachments.download', $attachment->short_url)}}" target="_blank" class="btn btn-sm btn-default"><i class="fa fa-fw fa-paperclip"></i> {{$attachment->title}}</a></li>
                                    @endforeach
                                </ul>
                            @endif
                        </div>
                    </div>
                @endforeach
            </div>
        @else
            <p>Tidak ada pesan terkait.</p>
        @endif
    </div>
</div>

@if(!$task->is_completed)
    <div class="panel panel-default">
        <div class="panel-heading">Pesan baru</div>
        {!! Former::open_for_files(route('admin.tasks.add_comment', $task->id)) !!}
            <div class="panel-body">
                {!! Former::textarea('text')->label('Pesan')->placeholder('pesan')->rows(5)->required() !!}
                {!! Former::file('lampiran[]')->label('Lampiran')->multiple()->help('tipe: .jpg, .jpeg, .png, .bmp, .pdf, .docx, .doc, .ppt, .pptx, .zip, .rar, .xls, .xlsx, Ukuran file: 8MB') !!}
            </div>
            <div class="panel-footer">
                <button class="btn btn-success"><i class="fa fa-fw fa-send"></i> Kirim pesan</button>
            </div>
        {!! Former::close() !!}
    </div>
@endif

resources/views/modules/admin/tasks/_detail_waiting.blade.php
{!! Former::populate($task) !!}
{!! Former::open_for_files(route('admin.tasks.update', $task->id)) !!}
    <div class="panel-body">
        {!! Former::text('title')->label('Judul')->required() !!}
        {!! Former::textarea('description')->label('Deskripsi')->rows(5) !!}
        {{-- {!! Former::file('lampiran[]')->label('Lampiran')->help('ukuran maksimum 10MB untuk tiap lampiran')->multiple() !!} --}}
    </div>
    <div class="panel-footer">
        <button class="btn btn-default">Update</button>
        <a href="{{route('admin.tasks.cancel', $task->id)}}" class="btn btn-cancel btn-danger">Batalkan</a>
    </div>
{!! Former::close() !!}

resources/views/modules/admin/tasks/completed.blade.php
@extends('layouts.admin')

@section('content')
<div id="task-unassigned-list-page">
    <ol class="breadcrumb flat">
        <li class="active"><a href="{{route('admin.tasks')}}">Tugas</a></li>
        <li class="active">Selesai</li>
    </ol>

    <div class="panel panel-default">
        <div class="panel-heading no-border-bottom">Tugas</div>
        <div class="panel-heading with-tab">
            <ul class="nav nav-tabs hidden-xs" role="tablist">
                <li role="presentation"><a href="{{route('admin.tasks')}}">Belum ditugaskan</a></li>
                <li role="presentation"><a href="{{route('admin.tasks.waiting_approval')}}">Menunggu Persetujuan</a></li>
                <li role="presentation"><a href="{{route('admin.tasks.ongoing')}}">Sedang Berjalan</a></li>
                <li role="presentation" class="active"><a href="{{route('admin.tasks.complete')}}">Selesai</a></li>
            </ul>
            <ul class="nav nav-tabs visible-xs" role="tablist">
                <li role="presentation" class="active dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" aria-controls="tab-dropdown" aria-expanded="false">Pilih <span class="caret"></span></a>
                    <ul class="dropdown-menu" id="tab-dropdown">
                        <li role="presentation"><a href="{{route('admin.tasks')}}">Belum ditugaskan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.waiting_approval')}}">Menunggu Persetujuan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.ongoing')}}">Sedang Berjalan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.complete')}}">Selesai</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        @if($tasks->count())
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Judul</th>
                            <th>Deskripsi</th>
                            <th>Progress</th>
                            <th>Diposting pada tgl</th>
                            <th>Diposting Oleh</th>
                            <th>Rating</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tasks as $task)
                            <tr>
                                <td>{{$task->id}}</td>
                                <td><a href="{{route('admin.tasks.detail', $task->id)}}">{{$task->title}}</a></td>
                                <td>{{str_limit($task->description, 50)}}</td>
                                <td>
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="{{$task->progress}}" aria-valuemin="0" aria-valuemax="100" style="width: {{$task->progress}}%;">{{$task->progress}}%</div>
                                    </div>
                                </td>
                                <td>{{$task->created_at}}</td>
                                <td>{{$task->postedby->name}}</td>
                                <td>
                                    @for($i = 0; $i < floor($task->rating->rating); $i++)
                                        <i class="fa fa-star bg-yellow"></i>
                                    @endfor

                                    @if(fmod($task->rating->rating, 1))
                                        <i class="fa fa-star-half bg-yellow"></i>
                                    @endif
                                </td>
                                <td><a href="{{route('admin.tasks.detail', $task->id)}}" class="btn btn-sm btn-default">Detil</a></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">{!! $tasks->links() !!}</div>
        @else
            <div class="panel-body">
                Tidak ada tugas.
            </div>
        @endif

    </div>

    <a href="javascript:;" data-toggle="modal" data-target="#modal-new-task" class="btn btn-success">Buat tugas baru</a>
</div>

{{-- Modal New Task  --}}
<div id="modal-new-task" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Tugas baru</h4>
            </div>
            {!! Former::open_for_files(route('admin.tasks.create'))->method('post') !!}
                <div class="modal-body">
                    {!! Former::text('title')->label('Judul')->placeholder('Judul')->required() !!}
                    {!! Former::textarea('description')->label('Deskripsi')->placeholder('Deskripsi tugas')->rows(5)->required() !!}
                    {!! Former::file('lampiran[]')->label('Lampiran')->help('ukuran maksimum 10MB untuk tiap lampiran')->multiple() !!}
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    <button class="btn btn-primary">Simpan</button>
                </div>
            {!! Former::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/modules/admin/tasks/index.blade.php
@extends('layouts.admin')

@section('content')
<div id="task-unassigned-list-page">
    <ol class="breadcrumb flat">
        <li class="active">Tugas</li>
    </ol>

    <div class="panel panel-default">
        <div class="panel-heading no-border-bottom">Tugas</div>
        <div class="panel-heading with-tab">
            <ul class="nav nav-tabs hidden-xs" role="tablist">
                <li role="presentation" class="active"><a href="{{route('admin.tasks')}}">Belum ditugaskan</a></li>
                <li role="presentation"><a href="{{route('admin.tasks.waiting_approval')}}">Menunggu Persetujuan</a></li>
                <li role="presentation"><a href="{{route('admin.tasks.ongoing')}}">Sedang Berjalan</a></li>
                <li role="presentation"><a href="{{route('admin.tasks.complete')}}">Selesai</a></li>
            </ul>
            <ul class="nav nav-tabs visible-xs" role="tablist">
                <li role="presentation" class="active dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" aria-controls="tab-dropdown" aria-expanded="false">Pilih <span class="caret"></span></a>
                    <ul class="dropdown-menu" id="tab-dropdown">
                        <li role="presentation"><a href="{{route('admin.tasks')}}">Belum ditugaskan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.waiting_approval')}}">Menunggu Persetujuan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.ongoing')}}">Sedang Berjalan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.complete')}}">Selesai</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        @if($tasks->count())
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Judul</th>
                            <th>Deskripsi</th>
                            <th>Diposting pada tgl</th>
                            <th>Diposting Oleh</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tasks as $task)
                            <tr>
                                <td>{{$task->id}}</td>
                                <td><a href="{{route('admin.tasks.detail', $task->id)}}">{{$task->title}}</a></td>
                                <td>{{str_limit($task->description, 50)}}</td>
                                <td>{{$task->created_at}}</td>
                                <td><a href="{{route('admin.experts.detail', $task->postedby->id)}}">{{$task->postedby->name}}</a></td>
                                <td>
                                    <a href="{{route('admin.tasks.detail', $task->id)}}" class="btn btn-sm btn-default">Detil</a>
                                    <a href="{{route('admin.tasks.assign.page', $task->id)}}" class="btn btn-sm btn-default">Penugasan</a>
                                    {{-- <a href="javascript:;" class="btn btn-assign btn-sm btn-default" data-task-id="{{$task->id}}" data-title="{{$task->title}}" data-desc="{{$task->description}}" data-toggle="modal" data-target="#modal-assign-task">Penugasan</a> --}}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">{!! $tasks->links() !!}</div>
        @else
            <div class="panel-body">
                Tidak ada tugas.
            </div>
        @endif
    </div>


    <a href="javascript:;" data-toggle="modal" data-target="#modal-new-task" class="btn btn-success">Buat tugas baru</a>


</div>

{{-- Modal New Task  --}}
<div id="modal-new-task" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Tugas baru</h4>
            </div>
            {!! Former::open_for_files(route('admin.tasks.create'))->method('post') !!}
                <div class="modal-body">
                    {!! Former::text('title')->label('Judul')->placeholder('Judul')->required() !!}
                    {!! Former::textarea('description')->label('Deskripsi')->placeholder('Deskripsi tugas')->rows(5)->required() !!}
                    {!! Former::file('lampiran[]')->label('Lampiran')->help('ukuran maksimum 10MB untuk tiap lampiran')->multiple() !!}
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    <button class="btn btn-primary">Simpan</button>
                </div>
            {!! Former::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/modules/admin/tasks/waiting.blade.php
@extends('layouts.admin')

@section('content')
<div id="task-unassigned-list-page">
    <ol class="breadcrumb flat">
        <li class="active"><a href="{{route('admin.tasks')}}">Tugas</a></li>
        <li class="active">Menunggu persetujuan</li>
    </ol>

    <div class="panel panel-default">
        <div class="panel-heading no-border-bottom">Tugas</div>
        <div class="panel-heading with-tab">
            <ul class="nav nav-tabs hidden-xs" role="tablist">
                <li role="presentation"><a href="{{route('admin.tasks')}}">Belum ditugaskan</a></li>
                <li role="presentation" class="active"><a href="{{route('admin.tasks.waiting_approval')}}">Menunggu Persetujuan</a></li>
                <li role="presentation"><a href="{{route('admin.tasks.ongoing')}}">Sedang Berjalan</a></li>
                <li role="presentation"><a href="{{route('admin.tasks.complete')}}">Selesai</a></li>
            </ul>
            <ul class="nav nav-tabs visible-xs" role="tablist">
                <li role="presentation" class="active dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" aria-controls="tab-dropdown" aria-expanded="false">Pilih <span class="caret"></span></a>
                    <ul class="dropdown-menu" id="tab-dropdown">
                        <li role="presentation"><a href="{{route('admin.tasks')}}">Belum ditugaskan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.waiting_approval')}}">Menunggu Persetujuan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.ongoing')}}">Sedang Berjalan</a></li>
                        <li role="presentation"><a href="{{route('admin.tasks.complete')}}">Selesai</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        @if($tasks->count())
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Judul</th>
                            <th>Deskripsi</th>
                            <th>Diposting pada tgl</th>
                            <th>Diposting oleh</th>
                            <th>Ditugaskan kepada</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tasks as $task)
                            <tr>
                                <td>{{$task->id}}</td>
                                <td><a href="{{route('admin.tasks.detail', $task->id)}}">{{$task->title}}</a></td>
                                <td>{{str_limit($task->description, 50)}}</td>
                                <td>{{$task->created_at}}</td>
                                <td><a href="{{route('admin.experts.detail', $task->postedby->id)}}">{{$task->postedby->name}}</a></td>
                                <td><a href="{{route('admin.experts.detail', $task->assignedto->id)}}">{{$task->assignedto->name}}</a></td>
                                <td>
                                    <a href="{{route('admin.tasks.detail', $task->id)}}" class="btn btn-sm btn-default">Detil</a>
                                    <a href="{{route('admin.tasks.assign.page', $task->id)}}" class="btn btn-sm btn-default">Penugasan</a>
                                    {{-- <a href="javascript:;" class="btn btn-assign btn-sm btn-default" data-task-id="{{$task->id}}" data-title="{{$task->title}}" data-desc="{{$task->description}}" data-toggle="modal" data-target="#modal-assign-task">Penugasan</a> --}}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">{!! $tasks->links() !!}</div>
        @else
            <div class="panel-body">
                Tidak ada tugas.
            </div>
        @endif

    </div>

    <a href="javascript:;" data-toggle="modal" data-target="#modal-new-task" class="btn btn-success">Buat tugas baru</a>
</div>


{{-- Modal New Task  --}}
<div id="modal-new-task" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Tugas baru</h4>
            </div>
            {!! Former::open(route('admin.tasks.create'))->method('post') !!}
                <div class="modal-body">
                    {!! Former::text('title')->label('Judul')->placeholder('Judul')->required() !!}
                    {!! Former::textarea('description')->label('Deskripsi')->placeholder('Deskripsi tugas')->required() !!}
                    {!! Former::file('lampiran[]')->label('Lampiran')->help('ukuran maksimum 10MB untuk tiap lampiran')->multiple() !!}
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    <button class="btn btn-primary">Simpan</button>
                </div>
            {!! Former::close() !!}
        </div>
    </div>
</div>
@endsection